plugins:
  - jekyll-paginate

title: Patti SUN
description: 照片、流水账、备忘录、一点点评论、不完整的草稿和引用的大杂烩

paginate: 10
paginate_path: /page/:num/
permalink: /:title/
social:
  小红书: https://www.xiaohongshu.com/user/profile/5af8ebe74eacab7dca2abc82
  微信公众号: https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzI1MDI2MTI1Mg==&action=getalbum&album_id=2512594468475404290&scene=126#wechat_redirect
  豆瓣： https://www.douban.com/people/153759825/?_i=1630515ziLWTRT,2761960zOpXY3x
  邮箱： xinyisun067@gmail.com
  
